Repository gii-is-psg2/PSG2-2021-G1-14, pull requests merged in 2021-05, with the labels that each got.

#67 Feature/65 adoptions tests
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: update

#68 Added fixes after Sprint Review
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/service/CauseService.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCause.jsp
  src/main/webapp/WEB-INF/jsp/causes/detailsCause.jsp
  src/main/webapp/WEB-INF/jsp/donations/createDonation.jsp
Labels: feature, fix

#69 Code Refactoring
  .vscode/launch.json
  .vscode/settings.json
  pom.xml
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/service/CauseService.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
  src/main/webapp/WEB-INF/jsp/donations/createDonation.jsp
Labels: bug, cleanup

#71 Final fixes for release 2.0.0
  src/main/java/org/springframework/samples/petclinic/PetclinicApplication.java
  src/main/java/org/springframework/samples/petclinic/model/Book.java
  src/main/java/org/springframework/samples/petclinic/repository/RequestRepository.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/RequestController.java
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/VetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/CrashControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetTypeFormatterTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VisitControllerTests.java
Labels: update

#70 Release/2.0.0
  .vscode/launch.json
  .vscode/settings.json
  pom.xml
  src/main/java/org/springframework/samples/petclinic/PetclinicApplication.java
  src/main/java/org/springframework/samples/petclinic/configuration/ExceptionHandlerConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/WebConfig.java
  src/main/java/org/springframework/samples/petclinic/model/Book.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/model/Request.java
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/repository/BookRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/CauseRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/DonationRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/RequestRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/service/CauseService.java
  src/main/java/org/springframework/samples/petclinic/service/DonationService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/DuplicatedRequestException.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/SameOwnerException.java
  src/main/java/org/springframework/samples/petclinic/util/BookValidator.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/PetTypeFormatter.java
  src/main/java/org/springframework/samples/petclinic/web/RequestController.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/java/org/springframework/samples/petclinic/web/VisitController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionsList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createOrUpdateRequestForm.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/requestList.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCause.jsp
  src/main/webapp/WEB-INF/jsp/causes/detailsCause.jsp
  src/main/webapp/WEB-INF/jsp/donations/createDonation.jsp
  src/main/webapp/WEB-INF/jsp/donations/donationDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/users/createOwnerForm.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/VetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/CrashControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetTypeFormatterTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VisitControllerTests.java
Labels: release

#72 Hotfix/2.0.1
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Veterinaries.java
  src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
  src/main/java/org/springframework/samples/petclinic/service/CauseService.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/web/BookController.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/RequestController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/test/java/org/springframework/samples/petclinic/model/ValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/service/CauseServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: bug, hotfix

#98 Feature/76 health
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/webapp/WEB-INF/tags/menu.tag
  system.properties
Labels: feature

#117 [A4.5.1.3] - Individual review/incident
  src/main/java/org/springframework/samples/petclinic/web/BookController.java
Labels: fix

#118 Fixed specialties issue
  src/main/java/org/springframework/samples/petclinic/web/BookController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: bug, fix

#120 Request on changing logo
  src/main/less/footer.less
  src/main/less/header.less
  src/main/less/petclinic.less
  src/main/resources/static/resources/images/footer.png
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
Labels: bug, feature

#119 Fixes for incident
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
Labels: fix

#122 Fix/106 specialties issue
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/webapp/WEB-INF/jsp/vets/createOrUpdateVetForm.jsp
Labels: fix

#123 Request on changing the color of the header/menu.
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/pivotal.tag
Labels: feature

#124 request/change-message-size
  src/main/less/typography.less
Labels: feature

#126 [A4.5.1.3] - Footer color changed
  src/main/webapp/WEB-INF/tags/footer.tag
Labels: feature

#127 New version 2.1.0
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/web/BookController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/less/footer.less
  src/main/less/header.less
  src/main/less/petclinic.less
  src/main/less/typography.less
  src/main/resources/static/resources/images/footer.png
  src/main/resources/static/resources/images/newlogo.png
  src/main/resources/static/resources/images/newlogo2.png
  src/main/resources/static/resources/images/wombat.jpg
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionsList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createOrUpdateRequestForm.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/requestList.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCause.jsp
  src/main/webapp/WEB-INF/jsp/causes/detailsCause.jsp
  src/main/webapp/WEB-INF/jsp/donations/createDonation.jsp
  src/main/webapp/WEB-INF/jsp/donations/donationDetails.jsp
  src/main/webapp/WEB-INF/jsp/exception.jsp
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/findOwners.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateBookForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateVisitForm.jsp
  src/main/webapp/WEB-INF/jsp/users/createOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/createOrUpdateVetForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetDetails.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/pivotal.tag
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
  system.properties
Labels: feature

#128 Revert "New version 2.1.0"
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/web/BookController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/less/footer.less
  src/main/less/header.less
  src/main/less/petclinic.less
  src/main/less/typography.less
  src/main/resources/static/resources/images/footer.png
  src/main/resources/static/resources/images/newlogo.png
  src/main/resources/static/resources/images/newlogo2.png
  src/main/resources/static/resources/images/wombat.jpg
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionsList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createOrUpdateRequestForm.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/requestList.jsp
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCause.jsp
  src/main/webapp/WEB-INF/jsp/causes/detailsCause.jsp
  src/main/webapp/WEB-INF/jsp/donations/createDonation.jsp
  src/main/webapp/WEB-INF/jsp/donations/donationDetails.jsp
  src/main/webapp/WEB-INF/jsp/exception.jsp
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/findOwners.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateBookForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateVisitForm.jsp
  src/main/webapp/WEB-INF/jsp/users/createOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/createOrUpdateVetForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetDetails.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/pivotal.tag
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
  system.properties
Labels: fix
