Repository gii-is-psg2/PSG2-2021-G1-14, pull requests merged in 2021-04, with the labels that each got.

#59 Epic/45 cause functionality
  .vscode/launch.json
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/repository/CauseRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/DonationRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/service/CauseService.java
  src/main/java/org/springframework/samples/petclinic/service/DonationService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/causes/causeList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createCause.jsp
  src/main/webapp/WEB-INF/jsp/causes/detailsCause.jsp
  src/main/webapp/WEB-INF/jsp/donations/createDonation.jsp
  src/main/webapp/WEB-INF/jsp/donations/donationDetails.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: cleanup, feature

#60 Task [3.2.2] - Pet hotel functionality validation
  src/main/java/org/springframework/samples/petclinic/configuration/ExceptionHandlerConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/WebConfig.java
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/repository/BookRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/DonationRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/service/DonationService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/util/BookValidator.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/PetTypeFormatter.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/java/org/springframework/samples/petclinic/web/VisitController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
Labels: cleanup, fix

#61 Feature/50 adoptions
  .vscode/launch.json
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/model/Request.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/RequestRepository.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/DuplicatedRequestException.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/SameOwnerException.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/RequestController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionsList.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/createOrUpdateRequestForm.jsp
  src/main/webapp/WEB-INF/jsp/adoptions/requestList.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/users/createOwnerForm.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: feature

#63 Final fixes before release 2.0.0
  src/main/java/org/springframework/samples/petclinic/model/Book.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
Labels: release
